# Generated by Django 5.2.3 on 2025-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='debut',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='release',
            field=models.TextField(),
        ),
    ]
