# Generated by Django 5.2.3 on 2025-07-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_singer_debut_alter_songs_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='singer',
        ),
    ]
