# Generated by Django 5.2.3 on 2025-07-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_songs_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='favorites.singer'),
        ),
    ]
