# Generated by Django 5.2.3 on 2025-07-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_songs_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='image',
        ),
        migrations.AlterField(
            model_name='songs',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='favorites.singer'),
        ),
    ]
