# Generated by Django 5.2.3 on 2025-07-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_remove_songs_image_alter_songs_singer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singer',
            new_name='Singers',
        ),
    ]
