# Generated by Django 5.2 on 2025-07-15 06:37

import favorites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_rename_singer_singers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='singers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=favorites.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='singers',
            name='tags',
            field=models.ManyToManyField(blank=True, to='favorites.tag'),
        ),
    ]
